/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamento.visao;

import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import estacionamento.cod.Estacionamento;
import estacionamento.modelo.Produto;

/**
 *
 * @author clodbrasilino
 */
public class JanelaProdutos extends javax.swing.JFrame {

    /**
     * Creates new form JanelaProdutos
     */
    public JanelaProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastrarProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        valorImpostoSlider = new javax.swing.JSlider();
        textoImposto = new javax.swing.JLabel();
        valorImpostoTextual = new javax.swing.JLabel();
        textoNomeProduto = new javax.swing.JLabel();
        caixaTextoNomeProduto = new javax.swing.JTextField();
        textoPreco = new javax.swing.JLabel();
        caixaTextoPreco = new javax.swing.JTextField();
        botaoApagarProduto = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produtos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        botaoCadastrarProduto.setText("+");
        botaoCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirNovoProduto(evt);
            }
        });

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        atualizarTabela();
        jScrollPane1.setViewportView(tabelaProdutos);

        valorImpostoSlider.setToolTipText("");
        valorImpostoSlider.setValue(0);
        valorImpostoSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                valorImpostoSliderStateChanged(evt);
            }
        });

        textoImposto.setText("Alíquota de Imposto: ");

        valorImpostoTextual.setText(valorImpostoSlider.getValue()+"%");

        textoNomeProduto.setText("Nome:");

        textoPreco.setText("Preço: ");

        caixaTextoPreco.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        caixaTextoPreco.setText("R$ 0,00");

        botaoApagarProduto.setText("-");
        botaoApagarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarProduto(evt);
            }
        });

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProduto(evt);
            }
        });

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarProduto(evt);
            }
        });
        botaoSalvar.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(textoImposto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorImpostoTextual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorImpostoSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(textoNomeProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caixaTextoNomeProduto))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(textoPreco)
                        .addGap(5, 5, 5)
                        .addComponent(caixaTextoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoApagarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoImposto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(valorImpostoTextual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(valorImpostoSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaTextoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNomeProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPreco)
                    .addComponent(caixaTextoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoApagarProduto)
                    .addComponent(botaoCadastrarProduto)
                    .addComponent(botaoEditar)
                    .addComponent(botaoSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    private void inserirNovoProduto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirNovoProduto
        String nome = caixaTextoNomeProduto.getText();
        Double aliquota = new Double(valorImpostoSlider.getValue())/100;
        String textoPreço = caixaTextoPreco.getText();
        textoPreço = textoPreço.replaceAll("R\\$\\ ", "");
        textoPreço = textoPreço.replaceAll(",", ".");
        Double preco = Double.parseDouble(textoPreço);
        try {
            funçao.inserirNoBanco(new Produto(null, nome, preco, aliquota));
        } catch (SQLException ex) {
            Logger.getLogger(JanelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        atualizarTabela();
    }//GEN-LAST:event_inserirNovoProduto

    private void valorImpostoSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_valorImpostoSliderStateChanged
        valorImpostoTextual.setText(valorImpostoSlider.getValue()+" %");
    }//GEN-LAST:event_valorImpostoSliderStateChanged

    private void apagarProduto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarProduto
        Integer linha = tabelaProdutos.getSelectedRow();
        Long id = Long.parseLong(
                tabelaProdutos
                    .getModel()
                    .getValueAt(linha, 0)
                    .toString()
        );
        try {
            funçao.apagarNoBanco(new Produto(id, null, null, null));
        } catch (SQLException ex) {
            Logger.getLogger(JanelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        atualizarTabela();
    }//GEN-LAST:event_apagarProduto

    private void editarProduto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProduto
        botaoCadastrarProduto.setVisible(false);
        botaoApagarProduto.setVisible(false);
        botaoEditar.setVisible(false);
        botaoSalvar.setVisible(true);
        
        int linha = tabelaProdutos.getSelectedRow();
        
        idSelecionado = (Long) tabelaProdutos.getModel().getValueAt(linha, 0);
        String nomeSelecionado = (String) tabelaProdutos.getModel().getValueAt(linha, 1);
        Double precoSelecionado = (Double) tabelaProdutos.getModel().getValueAt(linha, 2);
        String impostoSelecionado = (String) tabelaProdutos.getModel().getValueAt(linha, 3);
        
        Integer imposto = Integer.parseInt(
            impostoSelecionado.replaceAll("\\%", "").
                replaceAll("\\.[0-9]","")
        );
        
        valorImpostoSlider.setValue(imposto);
        caixaTextoNomeProduto.setText(nomeSelecionado);
        caixaTextoPreco.setText(precoSelecionado.toString());
    }//GEN-LAST:event_editarProduto

    private void salvarProduto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarProduto
        botaoCadastrarProduto.setVisible(true);
        botaoApagarProduto.setVisible(true);
        botaoEditar.setVisible(true);
        botaoSalvar.setVisible(false);
        
        Produto produtoAEditar = new Produto(
            idSelecionado,
            caixaTextoNomeProduto.getText(),
            Double.parseDouble(caixaTextoPreco.getText()),
            (new Double(valorImpostoSlider.getValue()))/100
        );
        
        try {
            funçao.editarNoBanco(produtoAEditar);
        } catch (SQLException ex) {
            Logger.getLogger(JanelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        atualizarTabela();
    }//GEN-LAST:event_salvarProduto
    
    private void atualizarTabela(){
        String[] nomesDasColunas = {"ID","Nome","Preço Unitário","Alíquota"};
        List<Produto> doBanco = new LinkedList<>();
        try {
            if(funçao == null) {
                funçao = new Estacionamento();
            }
            doBanco = funçao.obterProdutosDoBanco();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(JanelaProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        Object[][] matriz = new Object[doBanco.size()][nomesDasColunas.length];
        int linha = 0;
        for(Produto p: doBanco){
            matriz[linha][0] = p.id;
            matriz[linha][1] = p.descricao;
            matriz[linha][2] = p.precoUnitario;
            matriz[linha][3] = p.aliquota*100+"%";
            ++linha;
        }
        tabelaProdutos.setModel(new DefaultTableModel(matriz,nomesDasColunas));
    }
    

    private Estacionamento funçao;
    private Long idSelecionado = -1l;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoApagarProduto;
    private javax.swing.JButton botaoCadastrarProduto;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField caixaTextoNomeProduto;
    private javax.swing.JTextField caixaTextoPreco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JLabel textoImposto;
    private javax.swing.JLabel textoNomeProduto;
    private javax.swing.JLabel textoPreco;
    private javax.swing.JSlider valorImpostoSlider;
    private javax.swing.JLabel valorImpostoTextual;
    // End of variables declaration//GEN-END:variables
}
