/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estacionamento.visao;

import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import estacionamento.cod.Estacionamento;
import estacionamento.modelo.Venda;

/**
 *
 * @author clodbrasilino
 */
public class JanelaVendas extends javax.swing.JFrame {

    /**
     * Creates new form JanelaProdutos
     */
    public JanelaVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCadastrarVenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVendas = new javax.swing.JTable();
        textoCPF = new javax.swing.JLabel();
        caixaTextoCPF = new javax.swing.JTextField();
        textoTotal = new javax.swing.JLabel();
        botaoApagarVenda = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        textoValorTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        botaoCadastrarVenda.setText("+");
        botaoCadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirNovaVenda(evt);
            }
        });

        tabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        atualizarTabela();
        jScrollPane1.setViewportView(tabelaVendas);

        textoCPF.setText("CPF:");

        textoTotal.setText("Total: ");

        botaoApagarVenda.setText("-");
        botaoApagarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarProduto(evt);
            }
        });

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarProduto(evt);
            }
        });

        textoValorTotal.setText("     ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixaTextoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textoTotal)
                .addGap(18, 18, 18)
                .addComponent(textoValorTotal)
                .addGap(188, 188, 188))
            .addGroup(layout.createSequentialGroup()
                .addComponent(botaoCadastrarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoApagarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaTextoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCPF)
                    .addComponent(textoTotal)
                    .addComponent(textoValorTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastrarVenda)
                    .addComponent(botaoApagarVenda)
                    .addComponent(botaoEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    private void inserirNovaVenda(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirNovaVenda
        try {
            Venda novaVenda = new Venda(caixaTextoCPF.getText());
            funçao.inserirNoBanco(novaVenda);
            Venda venda = funçao.obterUltimaVendaDoBanco();
            
            java.awt.EventQueue.invokeLater(() -> {
                if(janelaItensDeVenda == null)
                    janelaItensDeVenda = new JanelaItensDeVenda(venda, self);
                janelaItensDeVenda.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                janelaItensDeVenda.setVisible(true);
            });
        } catch (SQLException ex) {
            Logger.getLogger(JanelaVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_inserirNovaVenda

    private void apagarProduto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarProduto
        
    }//GEN-LAST:event_apagarProduto

    private void editarProduto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarProduto
        
    }//GEN-LAST:event_editarProduto

    private void atualizarTabela(){
        String[] nomesDasColunas = {"ID","CPF","Total"};
        List<Venda> doBanco = new LinkedList<>();
        try {
            if(funçao == null) {
                funçao = new Estacionamento();
            }
            doBanco = funçao.obterVendasDoBanco();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(JanelaVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        Object[][] matriz = new Object[doBanco.size()][nomesDasColunas.length];
        int linha = 0;
        for(Venda v: doBanco){
            matriz[linha][0] = v.id;
            matriz[linha][1] = v.cpf;
            matriz[linha][2] = v.total;
            ++linha;
        }
        tabelaVendas.setModel(new DefaultTableModel(matriz,nomesDasColunas));
    }
    

    private Estacionamento funçao;
    private final JanelaVendas self = this;
    private final Long idSelecionado = -1l;
    private JanelaItensDeVenda janelaItensDeVenda;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoApagarVenda;
    private javax.swing.JButton botaoCadastrarVenda;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JTextField caixaTextoCPF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaVendas;
    private javax.swing.JLabel textoCPF;
    private javax.swing.JLabel textoTotal;
    private javax.swing.JLabel textoValorTotal;
    // End of variables declaration//GEN-END:variables
}
